<script lang="ts">
  import HomepageTemplate from '$lib/HomepageTemplate.svelte';
</script>

<HomepageTemplate
  locale="en"
  pageTitle="Free planning poker, no signup | CleanPoker"
  metaDesc="Free eco-designed planning poker. No behavioural tracking, no advertising cookies, zero ads. Under 50 KB JS. WCAG 2.1 AA accessible: full keyboard navigation, screen reader support (NVDA, VoiceOver). Green hosting. No account."
  canonical="https://cleanpoker.dev"
  ogLocale="en_US"
  ogTitle="Free planning poker, no signup | CleanPoker"
  ogDesc="Eco-designed, no behavioural tracking, no ads, WCAG 2.1 AA accessible. Create a session in one click. No account, green hosting on renewable energy."
  twitterTitle="Free planning poker, no signup | CleanPoker"
  twitterDesc="Eco-designed, no behavioural tracking, no ads, WCAG 2.1 AA accessible. Create a session in one click. No account, green hosting on renewable energy."
  jsonLdUrl="https://cleanpoker.dev"
  jsonLdDesc="Free collaborative planning poker tool. Eco-designed: no behavioural tracking, no advertising cookies, no ads, under 50 KB JS, green hosting on renewable energy. WCAG 2.1 AA accessible: keyboard navigation, screen reader support (NVDA, VoiceOver). No account required."
  accessibilitySummary="Fully keyboard navigable (Tab, Enter, Space). Compatible with NVDA and VoiceOver screen readers. aria-live regions for real-time vote updates. Minimum 4.5:1 contrast ratio. Skip link provided. No distracting animations. WCAG 2.1 AA compliant."
  keywords="planning poker, scrum, agile, sprint planning, eco-design, green IT, sustainable, no behavioural tracking, no advertising cookies, privacy, GDPR, accessible, WCAG 2.1 AA, screen reader, keyboard navigation, NVDA, VoiceOver, no account, green hosting, renewable energy, open source, MIT, Lighthouse 100"
  navAriaLabel="Language"
  h1Main="Planning poker:"
  h1Accent="create, vote, decide"
  lead="Create a session, share the URL, estimate as a team. Ready in one click."
  cardsLabel="Cards"
  cardsSepHint="(comma-separated)"
  presetsAriaLabel="Presets"
  minCardsError="Minimum 2 cards"
  createBtnLabel="Create a session"
  creatingLabel="Creating..."
  hintText="Share the link. That's it."
  createError="Unable to create the room. Please try again."
  footerSource="Source code"
  footerLicense="MIT License"
  footerAbout="About"
  footerLegal="Legal notice"
  footerPrivacy="Privacy"
/>
