<script lang="ts">
  import HomepageTemplate from '$lib/HomepageTemplate.svelte';
</script>

<HomepageTemplate
  locale="de"
  pageTitle="Planning Poker kostenlos, ohne Anmeldung | CleanPoker"
  metaDesc="Kostenloses, ökodesigntes Planning Poker. Kein verhaltensbasiertes Tracking, keine Werbe-Cookies, keine Werbung. Unter 50 KB JS. WCAG 2.1 AA barrierefrei: Tastaturnavigation, Screenreader (NVDA, VoiceOver). Grünes Hosting. Kein Konto."
  canonical="https://cleanpoker.dev/de"
  ogLocale="de_DE"
  ogTitle="Planning Poker kostenlos, ohne Anmeldung | CleanPoker"
  ogDesc="Ökodesignt, kein verhaltensbasiertes Tracking, keine Werbung, WCAG 2.1 AA barrierefrei. Session mit einem Klick erstellen. Kein Konto, grünes Hosting mit erneuerbarer Energie."
  twitterTitle="Planning Poker kostenlos, ohne Anmeldung | CleanPoker"
  twitterDesc="Ökodesignt, kein verhaltensbasiertes Tracking, keine Werbung, WCAG 2.1 AA barrierefrei. Session mit einem Klick erstellen. Kein Konto, grünes Hosting mit erneuerbarer Energie."
  jsonLdUrl="https://cleanpoker.dev/de"
  jsonLdDesc="Kostenloses kollaboratives Planning-Poker-Tool. Ökodesignt: kein verhaltensbasiertes Tracking, keine Werbe-Cookies, keine Werbung, unter 50 KB JS, grünes Hosting mit erneuerbarer Energie. WCAG 2.1 AA barrierefrei: Tastaturnavigation, Screenreader-Unterstützung (NVDA, VoiceOver). Kein Konto erforderlich."
  accessibilitySummary="Vollständige Tastaturnavigation (Tab, Eingabe, Leertaste). Kompatibel mit NVDA und VoiceOver Screenreadern. aria-live-Bereiche für Echtzeit-Updates. Mindestkontrastrate 4,5:1. Skip-Link vorhanden. Keine ablenkenden Animationen. WCAG 2.1 AA konform."
  keywords="Planning Poker, Scrum, Agile, Sprint Planning, Ökodesign, Green IT, nachhaltig, kein verhaltensbasiertes Tracking, keine Werbe-Cookies, Datenschutz, DSGVO, barrierefrei, WCAG 2.1 AA, Screenreader, Tastaturnavigation, NVDA, VoiceOver, kein Konto, grünes Hosting, erneuerbare Energie, Open Source, MIT"
  navAriaLabel="Sprache"
  h1Main="Planning Poker:"
  h1Accent="erstellen, abstimmen, entscheiden"
  lead="Session erstellen, Link teilen, gemeinsam schätzen. Mit einem Klick startklar."
  cardsLabel="Karten"
  cardsSepHint="(kommagetrennt)"
  presetsAriaLabel="Voreinstellungen"
  minCardsError="Mindestens 2 Karten"
  createBtnLabel="Session erstellen"
  creatingLabel="Erstelle..."
  hintText="Link teilen. Fertig."
  createError="Session konnte nicht erstellt werden. Bitte erneut versuchen."
  footerSource="Quellcode"
  footerLicense="MIT-Lizenz"
  footerAbout="Über CleanPoker"
  footerLegal="Impressum"
  footerPrivacy="Datenschutz"
/>
