<script lang="ts">
  import HomepageTemplate from '$lib/HomepageTemplate.svelte';
</script>

<HomepageTemplate
  locale="fr"
  pageTitle="Poker planning gratuit, sans inscription | CleanPoker"
  metaDesc="Outil de poker planning en ligne gratuit, sans inscription et sans trackers. Créez une session, partagez le lien, estimez en équipe. Éco-conçu, accessible WCAG 2.1 AA, hébergé en Europe."
  canonical="https://cleanpoker.dev/fr"
  ogLocale="fr_FR"
  ogTitle="Poker planning gratuit, sans inscription | CleanPoker"
  ogDesc="Éco-conçu, zéro trackers, zéro pub, accessible WCAG 2.1 AA. Créez une session en un clic. Aucun compte requis, hébergement sur énergie renouvelable."
  twitterTitle="Poker planning gratuit, sans inscription | CleanPoker"
  twitterDesc="Éco-conçu, zéro trackers, zéro pub, accessible WCAG 2.1 AA. Créez une session en un clic. Aucun compte requis, hébergement sur énergie renouvelable."
  jsonLdUrl="https://cleanpoker.dev/fr"
  jsonLdDesc="Outil de poker planning collaboratif, gratuit, éco-conçu et sans compte. Zéro trackers, zéro cookie publicitaire, zéro pub. Bundle JS < 50 Ko. Hébergement sur énergie renouvelable. Accessible WCAG 2.1 AA : navigation clavier, lecteurs d'écran NVDA et VoiceOver."
  accessibilitySummary="Navigation clavier complète (Tab, Entrée, Espace). Compatible avec les lecteurs d'écran NVDA et VoiceOver. Zones aria-live pour les mises à jour en temps réel. Ratio de contraste minimum 4,5:1. Lien d'évitement. Pas d'animation de distraction. Conforme WCAG 2.1 AA."
  keywords="poker planning, poker planning en ligne, poker planning gratuit, planning poker, scrum, agile, sprint planning, sans inscription, éco-conception, green IT, numérique responsable, zéro trackers, sans cookie publicitaire, vie privée, RGPD, accessible, WCAG 2.1 AA, lecteur d'écran, navigation clavier, NVDA, VoiceOver, sans compte, hébergement vert, énergie renouvelable, open source, MIT, Lighthouse 100"
  navAriaLabel="Langue"
  h1Main="Poker planning :"
  h1Accent="créer, voter, décider"
  lead="Créez une session de poker planning, partagez l'URL, estimez en équipe. Aucun compte requis."
  cardsLabel="Cartes"
  cardsSepHint="(séparées par des virgules)"
  presetsAriaLabel="Présélections"
  minCardsError="Minimum 2 cartes"
  createBtnLabel="Créer une session"
  creatingLabel="Création..."
  hintText="Partage le lien. C'est prêt."
  createError="Impossible de créer la salle. Réessaie."
  footerSource="Code source"
  footerLicense="Licence MIT"
  footerAbout="À propos"
  footerLegal="Mentions légales"
  footerPrivacy="Confidentialité"
/>
